import { type TokenMaps, camel } from "./parse.ts";
import { parseColor, toArgbHex, f } from "./color.ts";

const HEADER_LINES = [
  "GENERATED by @capecho/design-tokens — DO NOT EDIT.",
  "Source: design/tokens.css (DES-2).",
  "Regenerate: `bun run generate` in shared/design-tokens. CI fails on drift.",
];

/** Color tokens = keys in the light map whose value parses as a color. */
function colorKeys(maps: TokenMaps): string[] {
  return Object.keys(maps.light).filter((k) => parseColor(maps.light[k]!) !== null);
}

/** Base scalar tokens for the dimension table: px + unitless (weights, line-heights,
 *  optical sizes). `em` tracking is EXCLUDED — it's relative to font size, not an
 *  absolute point/logical-pixel value, so emitting it as a bare double would render
 *  the wrong letter-spacing (Codex M0b). em tracking stays in tokens.json with its unit. */
function scalarKeys(maps: TokenMaps): string[] {
  return Object.keys(maps.base).filter((k) => /^-?[\d.]+(px)?$/.test(maps.base[k]!));
}

function scalarValue(v: string): string {
  return v.replace(/px$/, "");
}

export function emitJson(maps: TokenMaps): string {
  return JSON.stringify(
    { _generated: "from design/tokens.css — do not edit", ...maps },
    null,
    2,
  ) + "\n";
}

export function emitDart(maps: TokenMaps): string {
  const colors = colorKeys(maps);
  const scalars = scalarKeys(maps);
  const L: string[] = [];
  for (const h of HEADER_LINES) L.push(`// ${h}`);
  L.push("import 'dart:ui';", "");
  L.push("/// Caffeine + Warm-Glass color tokens (light + dark).");
  L.push("class CapechoColors {");
  for (const k of colors) L.push(`  final Color ${camel(k)};`);
  L.push(`  const CapechoColors({${colors.map((k) => `required this.${camel(k)}`).join(", ")}});`);
  L.push("");
  L.push("  static const CapechoColors light = CapechoColors(");
  for (const k of colors) L.push(`    ${camel(k)}: Color(${toArgbHex(parseColor(maps.light[k]!)!)}),`);
  L.push("  );");
  L.push("  static const CapechoColors dark = CapechoColors(");
  for (const k of colors) {
    const v = maps.dark[k] ?? maps.light[k]!;
    L.push(`    ${camel(k)}: Color(${toArgbHex(parseColor(v)!)}),`);
  }
  L.push("  );");
  L.push("}", "");
  L.push("/// Mode-agnostic scalar tokens (type sizes/weights/line-heights/tracking, spacing, radii).");
  L.push("class CapechoDimens {");
  for (const k of scalars) L.push(`  static const double ${camel(k)} = ${scalarValue(maps.base[k]!)};`);
  L.push("}", "");
  return L.join("\n");
}

export function emitSwift(maps: TokenMaps): string {
  const colors = colorKeys(maps);
  const scalars = scalarKeys(maps);
  const L: string[] = [];
  for (const h of HEADER_LINES) L.push(`// ${h}`);
  L.push("import SwiftUI", "");
  const colorInit = (k: string, src: Record<string, string>, fallback: Record<string, string>) => {
    const c = parseColor(src[k] ?? fallback[k]!)!;
    return `Color(.sRGB, red: ${f(c.r / 255)}, green: ${f(c.g / 255)}, blue: ${f(c.b / 255)}, opacity: ${f(c.a)})`;
  };
  L.push("/// Caffeine + Warm-Glass color tokens (light + dark).");
  L.push("public struct CapechoColors {");
  for (const k of colors) L.push(`    public let ${camel(k)}: Color`);
  L.push("");
  L.push("    public static let light = CapechoColors(");
  L.push(colors.map((k) => `        ${camel(k)}: ${colorInit(k, maps.light, maps.light)}`).join(",\n"));
  L.push("    )");
  L.push("    public static let dark = CapechoColors(");
  L.push(colors.map((k) => `        ${camel(k)}: ${colorInit(k, maps.dark, maps.light)}`).join(",\n"));
  L.push("    )");
  L.push("}", "");
  L.push("/// Mode-agnostic scalar tokens.");
  L.push("public enum CapechoDimens {");
  for (const k of scalars) L.push(`    public static let ${camel(k)}: CGFloat = ${scalarValue(maps.base[k]!)}`);
  L.push("}", "");
  return L.join("\n");
}
